# Basic Site Settings
locale                   : "en-US"
title                    : "Michael Liu"
url                      : https://BV003.github.io
baseurl                  : ""

# Reading Files
include:
  - _pages
  - files
exclude:
  - Gemfile
  - Gemfile.lock
encoding: "utf-8"

# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
